# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app/airlive main.go"
bin = "tmp/app"

full_bin = "./tmp/app/airlive"
log = "air_errors.log"
include_ext = ["go", "yaml"]
exclude_dir = ["tmp"]
delay = 1000 # ms

[log]
time = true

[misc]
clean_on_exit = true